#!/bin/bash
 
#SBATCH --job-name 010-1
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 20 
#SBATCH --mem 58000
#SBATCH -t 180:00:00
#SBATCH --mail-type ALL
#SBATCH --mail-user meeri.lembinen@gmail.com

name=EMImCCN3

module load gpaw-1.3.0 

mpirun -np 20 gpaw-python $name\_gs.py> $name\.out


